services:
#    cloud_twilio_wrapper.example:
#        class: Cloud\TwilioWrapperBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    commcloud_twilio_wrapper.twilio_api:
        class: Commcloud\VoiceBundle\Service\TwilioWrapper
    commcloud_twilio_wrapper.twilio_capability:
        class: Commcloud\VoiceBundle\Service\TwilioCapabilityWrapper
    commcloud_twilio_wrapper.twilio_taskrouter:
        class: Commcloud\VoiceBundle\Service\TwilioTaskRouterWrapper
    commcloud_twilio_wrapper.twilio_taskrouter_worker_capability:
        class: Commcloud\VoiceBundle\Service\TwilioTaskRouterWorkerCapabilityWrapper