<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * CronTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
