<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * EventDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventDataRepository extends \Doctrine\ORM\EntityRepository
{
}
