<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * HtReservationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtReservationDataRepository extends \Doctrine\ORM\EntityRepository
{
}
