<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * HtTaskqueueDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtTaskqueueDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByStartTime($taskqueuesid, $starttime, $endtime)
    {        
        $repository = $this->getEntityManager()
                            ->getRepository('CommcloudVoiceBundle:HtTaskqueueData');
        $query = $repository->createquerybuilder('p')
                                ->where('p.taskqueuesid = :wsid and p.start_time between :starttime and :endtime')
                                ->setParameter('wsid', $taskqueuesid)
                                ->setParameter('starttime',$starttime)
                                ->setParameter('endtime', $endtime)
                                ->groupBy('p.start_time')
                                ->orderBy('p.start_time', 'ASC')
                                ->getQuery();
        
        return $query->getResult();
        
    }    
}
