<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * HtWorkflowDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtWorkflowDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByStartTime($workflowsid, $starttime, $endtime)
    {        
        $repository = $this->getEntityManager()
                            ->getRepository('CommcloudVoiceBundle:HtWorkflowData');
        $query = $repository->createquerybuilder('p')
                                ->where('p.workflowsid = :wsid and p.start_time between :starttime and :endtime')
                                ->setParameter('wsid', $workflowsid)
                                ->setParameter('starttime',$starttime)
                                ->setParameter('endtime', $endtime)
                                ->groupBy('p.start_time')
                                ->orderBy('p.start_time', 'ASC')
                                ->getQuery();
        
        return $query->getResult();
        
    }
}
