<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * TaskEventDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskEventDataRepository extends \Doctrine\ORM\EntityRepository
{
}
