<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
