<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
