<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WorkerInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
