<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WorkerEventDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerEventDataRepository extends \Doctrine\ORM\EntityRepository
{
}
