<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WTaskqueuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WTaskqueuesRepository extends \Doctrine\ORM\EntityRepository
{
}
