<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WWorkflowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WWorkflowsRepository extends \Doctrine\ORM\EntityRepository
{
}
