<?php

namespace Commcloud\VoiceBundle\Repository;

/**
 * WWorkspacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WWorkspacesRepository extends \Doctrine\ORM\EntityRepository
{
}
