<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WWorkflows extends \Commcloud\VoiceBundle\Entity\WWorkflows implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'friendlyName', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'accountSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'workspaceSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'assignmentCallbackUrl', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'fallbackAssignmentCallbackUrl', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'configuration', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'taskReservationTimeout', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'dateCreated', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'dateUpdated', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'status', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'sid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'workflowSid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'friendlyName', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'accountSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'workspaceSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'assignmentCallbackUrl', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'fallbackAssignmentCallbackUrl', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'configuration', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'taskReservationTimeout', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'dateCreated', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'dateUpdated', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'status', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'sid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WWorkflows' . "\0" . 'workflowSid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WWorkflows $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFriendlyName($friendlyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFriendlyName', [$friendlyName]);

        return parent::setFriendlyName($friendlyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFriendlyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFriendlyName', []);

        return parent::getFriendlyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountSid($accountSid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountSid', [$accountSid]);

        return parent::setAccountSid($accountSid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountSid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountSid', []);

        return parent::getAccountSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkspaceSid($workspaceSid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkspaceSid', [$workspaceSid]);

        return parent::setWorkspaceSid($workspaceSid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspaceSid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspaceSid', []);

        return parent::getWorkspaceSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignmentCallbackUrl($assignmentCallbackUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignmentCallbackUrl', [$assignmentCallbackUrl]);

        return parent::setAssignmentCallbackUrl($assignmentCallbackUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignmentCallbackUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignmentCallbackUrl', []);

        return parent::getAssignmentCallbackUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallbackAssignmentCallbackUrl($fallbackAssignmentCallbackUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallbackAssignmentCallbackUrl', [$fallbackAssignmentCallbackUrl]);

        return parent::setFallbackAssignmentCallbackUrl($fallbackAssignmentCallbackUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallbackAssignmentCallbackUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallbackAssignmentCallbackUrl', []);

        return parent::getFallbackAssignmentCallbackUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfiguration($configuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfiguration', [$configuration]);

        return parent::setConfiguration($configuration);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguration', []);

        return parent::getConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskReservationTimeout($taskReservationTimeout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskReservationTimeout', [$taskReservationTimeout]);

        return parent::setTaskReservationTimeout($taskReservationTimeout);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskReservationTimeout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskReservationTimeout', []);

        return parent::getTaskReservationTimeout();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated($dateUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', [$dateUpdated]);

        return parent::setDateUpdated($dateUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', []);

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getSid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSid', []);

        return parent::getSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflowSid($workflowSid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowSid', [$workflowSid]);

        return parent::setWorkflowSid($workflowSid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowSid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowSid', []);

        return parent::getWorkflowSid();
    }

}
