<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaskEventData extends \Commcloud\VoiceBundle\Entity\TaskEventData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'tasksid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskattributes', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskage', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskpriority', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskassignmentstatus', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskcancelledreason', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskcompletedreason'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'tasksid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskattributes', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskage', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskpriority', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskassignmentstatus', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskcancelledreason', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\TaskEventData' . "\0" . 'taskcompletedreason'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TaskEventData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTasksid($tasksid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTasksid', [$tasksid]);

        return parent::setTasksid($tasksid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTasksid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTasksid', []);

        return parent::getTasksid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskattributes($taskattributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskattributes', [$taskattributes]);

        return parent::setTaskattributes($taskattributes);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskattributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskattributes', []);

        return parent::getTaskattributes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskage($taskage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskage', [$taskage]);

        return parent::setTaskage($taskage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskage', []);

        return parent::getTaskage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskpriority($taskpriority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskpriority', [$taskpriority]);

        return parent::setTaskpriority($taskpriority);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskpriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskpriority', []);

        return parent::getTaskpriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskassignmentstatus($taskassignmentstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskassignmentstatus', [$taskassignmentstatus]);

        return parent::setTaskassignmentstatus($taskassignmentstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskassignmentstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskassignmentstatus', []);

        return parent::getTaskassignmentstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskcancelledreason($taskcancelledreason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskcancelledreason', [$taskcancelledreason]);

        return parent::setTaskcancelledreason($taskcancelledreason);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskcancelledreason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskcancelledreason', []);

        return parent::getTaskcancelledreason();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskcompletedreason($taskcompletedreason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskcompletedreason', [$taskcompletedreason]);

        return parent::setTaskcompletedreason($taskcompletedreason);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskcompletedreason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskcompletedreason', []);

        return parent::getTaskcompletedreason();
    }

}
