<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EventData extends \Commcloud\VoiceBundle\Entity\EventData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'eventtype', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'accountsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workspacesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workspacename', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'eventdescription', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'resourcetype', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'resourcesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'timestamp', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workflowsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'taskqueuesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'reservationsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workersid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'tasksid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'eventtype', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'accountsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workspacesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workspacename', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'eventdescription', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'resourcetype', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'resourcesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'timestamp', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workflowsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'taskqueuesid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'reservationsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'workersid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\EventData' . "\0" . 'tasksid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EventData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventtype($eventtype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventtype', [$eventtype]);

        return parent::setEventtype($eventtype);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventtype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventtype', []);

        return parent::getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountsid($accountsid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountsid', [$accountsid]);

        return parent::setAccountsid($accountsid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountsid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountsid', []);

        return parent::getAccountsid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkspacesid($workspacesid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkspacesid', [$workspacesid]);

        return parent::setWorkspacesid($workspacesid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspacesid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspacesid', []);

        return parent::getWorkspacesid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkspacename($workspacename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkspacename', [$workspacename]);

        return parent::setWorkspacename($workspacename);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspacename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspacename', []);

        return parent::getWorkspacename();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventdescription($eventdescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventdescription', [$eventdescription]);

        return parent::setEventdescription($eventdescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventdescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventdescription', []);

        return parent::getEventdescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourcetype($resourcetype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourcetype', [$resourcetype]);

        return parent::setResourcetype($resourcetype);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourcetype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourcetype', []);

        return parent::getResourcetype();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourcesid($resourcesid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourcesid', [$resourcesid]);

        return parent::setResourcesid($resourcesid);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourcesid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourcesid', []);

        return parent::getResourcesid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp($timestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflowsid($workflowsid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowsid', [$workflowsid]);

        return parent::setWorkflowsid($workflowsid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowsid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowsid', []);

        return parent::getWorkflowsid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskqueuesid($taskqueuesid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskqueuesid', [$taskqueuesid]);

        return parent::setTaskqueuesid($taskqueuesid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskqueuesid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskqueuesid', []);

        return parent::getTaskqueuesid();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsid($reservationsid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsid', [$reservationsid]);

        return parent::setReservationsid($reservationsid);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsid', []);

        return parent::getReservationsid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkersid($workersid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkersid', [$workersid]);

        return parent::setWorkersid($workersid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkersid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkersid', []);

        return parent::getWorkersid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTasksid($tasksid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTasksid', [$tasksid]);

        return parent::setTasksid($tasksid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTasksid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTasksid', []);

        return parent::getTasksid();
    }

}
