<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HtReservationData extends \Commcloud\VoiceBundle\Entity\HtReservationData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'resourceid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'start_time', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'end_time', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservation_accepted', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_canceled', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_created', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_timed_out', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_rejected', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_rescinded'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'id', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'resourceid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'start_time', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'end_time', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservation_accepted', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_canceled', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_created', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_timed_out', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_rejected', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\HtReservationData' . "\0" . 'reservations_rescinded'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HtReservationData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceid($resourceid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceid', [$resourceid]);

        return parent::setResourceid($resourceid);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceid', []);

        return parent::getResourceid();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartTime($startTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartTime', [$startTime]);

        return parent::setStartTime($startTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartTime', []);

        return parent::getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime($endTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        return parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationAccepted($reservationAccepted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationAccepted', [$reservationAccepted]);

        return parent::setReservationAccepted($reservationAccepted);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationAccepted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationAccepted', []);

        return parent::getReservationAccepted();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsCanceled($reservationsCanceled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsCanceled', [$reservationsCanceled]);

        return parent::setReservationsCanceled($reservationsCanceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsCanceled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsCanceled', []);

        return parent::getReservationsCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsCreated($reservationsCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsCreated', [$reservationsCreated]);

        return parent::setReservationsCreated($reservationsCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsCreated', []);

        return parent::getReservationsCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsTimedOut($reservationsTimedOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsTimedOut', [$reservationsTimedOut]);

        return parent::setReservationsTimedOut($reservationsTimedOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsTimedOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsTimedOut', []);

        return parent::getReservationsTimedOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsRejected($reservationsRejected)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsRejected', [$reservationsRejected]);

        return parent::setReservationsRejected($reservationsRejected);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsRejected()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsRejected', []);

        return parent::getReservationsRejected();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationsRescinded($reservationsRescinded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationsRescinded', [$reservationsRescinded]);

        return parent::setReservationsRescinded($reservationsRescinded);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationsRescinded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationsRescinded', []);

        return parent::getReservationsRescinded();
    }

}
