<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkerInfo extends \Commcloud\VoiceBundle\Entity\WorkerInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wfname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wlname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wdisplayname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wskills', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wpass', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wemail', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wstatus', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wloginid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wroles', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'isActive'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wfname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wlname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wdisplayname', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wskills', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wpass', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wemail', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wstatus', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wsid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wloginid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'wroles', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WorkerInfo' . "\0" . 'isActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WorkerInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setWfname($wfname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWfname', [$wfname]);

        return parent::setWfname($wfname);
    }

    /**
     * {@inheritDoc}
     */
    public function getWfname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWfname', []);

        return parent::getWfname();
    }

    /**
     * {@inheritDoc}
     */
    public function setWlname($wlname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWlname', [$wlname]);

        return parent::setWlname($wlname);
    }

    /**
     * {@inheritDoc}
     */
    public function getWlname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWlname', []);

        return parent::getWlname();
    }

    /**
     * {@inheritDoc}
     */
    public function setWpass($wpass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWpass', [$wpass]);

        return parent::setWpass($wpass);
    }

    /**
     * {@inheritDoc}
     */
    public function getWpass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWpass', []);

        return parent::getWpass();
    }

    /**
     * {@inheritDoc}
     */
    public function setWemail($wemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWemail', [$wemail]);

        return parent::setWemail($wemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getWemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWemail', []);

        return parent::getWemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setWstatus($wstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWstatus', [$wstatus]);

        return parent::setWstatus($wstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getWstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWstatus', []);

        return parent::getWstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setWsid($wsid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWsid', [$wsid]);

        return parent::setWsid($wsid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWsid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWsid', []);

        return parent::getWsid();
    }

    /**
     * {@inheritDoc}
     */
    public function getWloginid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getWloginid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWloginid', []);

        return parent::getWloginid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWroles($wroles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWroles', [$wroles]);

        return parent::setWroles($wroles);
    }

    /**
     * {@inheritDoc}
     */
    public function getWroles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWroles', []);

        return parent::getWroles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setWdisplayname($wdisplayname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWdisplayname', [$wdisplayname]);

        return parent::setWdisplayname($wdisplayname);
    }

    /**
     * {@inheritDoc}
     */
    public function getWdisplayname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWdisplayname', []);

        return parent::getWdisplayname();
    }

    /**
     * {@inheritDoc}
     */
    public function setWskills($wskills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWskills', [$wskills]);

        return parent::setWskills($wskills);
    }

    /**
     * {@inheritDoc}
     */
    public function getWskills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWskills', []);

        return parent::getWskills();
    }

}
