<?php

namespace Proxies\__CG__\Commcloud\VoiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WActivity extends \Commcloud\VoiceBundle\Entity\WActivity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'accountSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'workspaceSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'friendlyName', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'available', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'status', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'sid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'activitySid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'accountSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'workspaceSid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'friendlyName', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'available', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'status', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'sid', '' . "\0" . 'Commcloud\\VoiceBundle\\Entity\\WActivity' . "\0" . 'activitySid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WActivity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSid($sid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSid', [$sid]);

        return parent::setSid($sid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSid', []);

        return parent::getSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFriendlyName($friendlyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFriendlyName', [$friendlyName]);

        return parent::setFriendlyName($friendlyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFriendlyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFriendlyName', []);

        return parent::getFriendlyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable($available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', [$available]);

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailable', []);

        return parent::getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountSid($accountSid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountSid', [$accountSid]);

        return parent::setAccountSid($accountSid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountSid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountSid', []);

        return parent::getAccountSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkspaceSid($workspaceSid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkspaceSid', [$workspaceSid]);

        return parent::setWorkspaceSid($workspaceSid);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspaceSid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspaceSid', []);

        return parent::getWorkspaceSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivitySid($activitySid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivitySid', [$activitySid]);

        return parent::setActivitySid($activitySid);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivitySid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivitySid', []);

        return parent::getActivitySid();
    }

}
